{% set name = "nifti_clib" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NIFTI-Imaging/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: fe6cb1076974df01844f3f4dab1aa844953b3bc1d679126c652975158573d03d
  # for local testing of the recipe use the following  
  #   -    git_url: /local/nifti_clib/

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    # If changing cmake version see:
    # https://github.com/conda-forge/cmake-feedstock/issues/106
    - cmake<3.13.4
    - {{ compiler('c') }}
    - help2man
  host:
    - zlib

test:
  commands:
    # make existence checks for some expected files
    - test -f ${PREFIX}/include/nifti/nifti1.h
    - test -f ${PREFIX}/include/nifti/nifti2.h
    - test -f ${PREFIX}/lib/libniftiio.a
    - test -f ${PREFIX}/lib/libniftiio$SHLIB_EXT
    - test -f ${PREFIX}/lib/libnifti2.a
    - test -f ${PREFIX}/lib/libnifti2$SHLIB_EXT
    - test -f ${PREFIX}/bin/nifti_tool
    # check that headers have not been inappropriately installed
    - test ! -f ${PREFIX}/include/nifti1.h

about:
  home: https://github.com/NIFTI-Imaging/nifti_clib
  license: Public Domain
  license_family: PUBLIC-DOMAIN
  license_file: LICENSE
  summary: 'C library for IO with the nifti file format.'

extra:
  recipe-maintainers:
    - leej3
