{% set name = "nifti_clib" %}
{% set version = "2.0.0" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://github.com/NIFTI-Imaging/{{ name }}/archive/de2bb84d6219a3671ef7f5b696f17d93276da9eb.tar.gz

build:
    number: 0
    skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - zlib
    - expat
  run:
    - expat
    - zlib

test:
    commands:

about:
    home: https://github.com/NIFTI-Imaging/nifti_clib
    license: Public Domain
    license_file: LICENSE.txt
    summary: 'C library for IO with the nifti file format.'

extra:
    recipe-maintainers:
        - leej3
